In [3]:
#CSV Bibliothek importieren 
import csv
#Pandas importieren und als pd bezeichnen
import pandas as pd
#Numpy importieren und als np bezeichnen 
import numpy as np
#Json Biliothek importieren
import json
#Obere Schranke für die Größe der Daten auf 100,000,000 setzen  
csv.field_size_limit(100000000)
#Maximale Anzahl von Zeilen und Spalten Zeigen 
pd.options.display.max_columns = None
pd.options.display.max_rows = None
#Extraktion der Domäne
import tldextract

***

### Pro_science domains

In [8]:
path = '../data/df_domains_pro_anti_science.tsv'

df_domains_pro_and_anti_science = pd.read_csv(path, sep='\t', error_bad_lines=False)

In [9]:
print('Shape: ', df_domains_pro_and_anti_science.shape)
df_domains_pro_and_anti_science.head()

Shape:  (1395, 4)

,domain,mediabias_proscience,mediabias_questionblesources,mediabias_conspiracy_psydoscience
0,Covid.gov,1.0,0.0,0.0
1,Drugs.com,1.0,0.0,0.0
2,News-Medical.net,1.0,0.0,0.0
3,SciTechDaily.com,1.0,0.0,0.0
4,aaas.org,1.0,0.0,0.0

In [10]:
df_proscience_domains = df_domains_pro_and_anti_science[df_domains_pro_and_anti_science['mediabias_proscience'] == 1]

print('Shape: ', df_proscience_domains.shape)
df_proscience_domains.head()

Shape:  (150, 4)

,domain,mediabias_proscience,mediabias_questionblesources,mediabias_conspiracy_psydoscience
0,Covid.gov,1.0,0.0,0.0
1,Drugs.com,1.0,0.0,0.0
2,News-Medical.net,1.0,0.0,0.0
3,SciTechDaily.com,1.0,0.0,0.0
4,aaas.org,1.0,0.0,0.0

In [11]:
list_proscience_domains = df_proscience_domains.domain.tolist()

In [12]:
def get_unique_items(l1):
    l1 = np.array(l1)
    l1 = np.unique(l1)
    l1 = l1.tolist()
    
    return l1

In [13]:
list_proscience_domains = get_unique_items(list_proscience_domains)
len(list_proscience_domains)

150

***

## Anti_science

***

In [14]:
df_domains_questionblesources = df_domains_pro_and_anti_science[df_domains_pro_and_anti_science['mediabias_questionblesources'] == 1]

print('Shape: ', df_domains_questionblesources.shape)
df_domains_questionblesources.head()

Shape:  (908, 4)

,domain,mediabias_proscience,mediabias_questionblesources,mediabias_conspiracy_psydoscience
150,100percentfedup.com,0.0,1.0,0.0
151,12minutos.com,0.0,1.0,0.0
152,2020conservative.com,0.0,1.0,0.0
153,24Jours.com,0.0,1.0,0.0
154,4Chan.org,0.0,1.0,0.0

In [15]:
list_domains_questionblesources = df_domains_questionblesources.domain.tolist()

In [16]:
df_domains_conspiracy_psydoscience = df_domains_pro_and_anti_science[df_domains_pro_and_anti_science['mediabias_conspiracy_psydoscience'] == 1]

print('Shape: ', df_domains_conspiracy_psydoscience.shape)
df_domains_conspiracy_psydoscience.head()

Shape:  (337, 4)

,domain,mediabias_proscience,mediabias_questionblesources,mediabias_conspiracy_psydoscience
1058,2020ElectionCenter.com,0.0,0.0,1.0
1059,21stcenturywire.com,0.0,0.0,1.0
1060,369news.net,0.0,0.0,1.0
1061,79Days.News,0.0,0.0,1.0
1062,911truth.org,0.0,0.0,1.0

In [17]:
list_domains_conspiracy_psydoscience = df_domains_conspiracy_psydoscience.domain.tolist()

In [18]:
list_antiscience_domains = []
list_antiscience_domains.extend(list_domains_conspiracy_psydoscience)
list_antiscience_domains.extend(list_domains_questionblesources)

list_antiscience_domains = get_unique_items(list_antiscience_domains)
len(list_antiscience_domains)

1245

## Polarisierungen berechnen
### TweetsCov19

---

In [13]:
path = '../data/tweetscov19_id_isdeleted_domains.tsv'

df_tweetscov19 = pd.read_csv(path, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username' ,'Is_deleted', 'Domains'])

print('Shape :', df_tweetscov19.shape)
df_tweetscov19.head()

Shape : (9409841, 4)

,Tweet_Id,Username,Is_deleted,Domains
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0

In [14]:
def get_number_of_antiscience_domains(domains):
    domains_list = domains.split()
    score = 0
    l = []
    for i in range(0, len(domains_list)):
        
        #d = tldextract.extract(domains_list[i])
        #d = d.domain          
        d = domains_list[i]
        
        if d in list_antiscience_domains:
            score -=  1
            l.append(d)
        
    return l

In [15]:
df_tweetscov19['Domains'] = df_tweetscov19['Domains'].astype(str)

df_tweetscov19['Antisciens_domains'] = df_tweetscov19.apply(lambda row: get_number_of_antiscience_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [16]:
df_tweetscov19.head()

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[]
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0,0

In [18]:
df_tweetscov19['number_of_antisciens_domains'] = df_tweetscov19.apply(lambda row: len(row['Antisciens_domains']) if (row['Antisciens_domains'] != 0) else 0, axis=1)

In [19]:
df_tweetscov19[df_tweetscov19.number_of_antisciens_domains > 1].head()

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,number_of_antisciens_domains
11047,1179022999145586690,714e9cc02aac6bcefdc580a376e2f514,True,banned.video naturalnews.com summit.news infow...,"[naturalnews.com, infowars.com, infowars.com]",3
23565,1179228423727788042,40ac9f8593dce049547de6f85b61f96c,False,xinhuanet.com xinhuanet.com xinhuanet.com,"[xinhuanet.com, xinhuanet.com, xinhuanet.com]",3
55195,1179847414771060737,d8eb2a8123c267ebb4e4b317ad238f77,True,acpeds.org dailymail.co.uk,"[acpeds.org, dailymail.co.uk]",2
109099,1180923634648371200,ebc1956f29c065535666c29319c902bc,True,townhall.com pjmedia.com facebook.com,"[townhall.com, pjmedia.com]",2
117794,1181094388967116800,40ac9f8593dce049547de6f85b61f96c,False,xinhuanet.com xinhuanet.com xinhuanet.com,"[xinhuanet.com, xinhuanet.com, xinhuanet.com]",3

In [20]:
def get_number_of_proscience_domains(domains):
    domains_list = domains.split()
    score = 0
    l = []
    for i in range(0, len(domains_list)):
        
        #d = tldextract.extract(domains_list[i])
        #d = d.domain
       
            
        d = domains_list[i]
        if d in list_proscience_domains:
            score +=  1
            l.append(d)
        
    return l

In [21]:
df_tweetscov19['Prosciens_domains'] = df_tweetscov19.apply(lambda row: get_number_of_proscience_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [22]:
df_tweetscov19.head()

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,number_of_antisciens_domains,Prosciens_domains
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0,0,0,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[],0,[]
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0,0,0,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0,0,0,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0,0,0,0

In [23]:
df_tweetscov19['Number_of_prosciens_domains'] = df_tweetscov19.apply(lambda row: len(row['Prosciens_domains']) if (row['Prosciens_domains'] != 0) else 0, axis=1)

In [24]:
df_tweetscov19[df_tweetscov19.number_of_prosciens_domains > 1].head()

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,number_of_antisciens_domains,Prosciens_domains,number_of_prosciens_domains
6628,1178932195915780097,e1e58ab93d4bf933378b761a8d9da89d,False,thinkingautism.org.uk nih.gov hopkinsmedicine.org,[],0,"[nih.gov, hopkinsmedicine.org]",2
14888,1179076769372086275,86ab42ac9de2e686351179e971a0baec,False,aps.org aps.org,[],0,"[aps.org, aps.org]",2
65626,1180051252996169728,5bec8c0e4b6f411c232d568bb8420696,False,physiology.org sciencedirect.com sciencedirect...,[],0,"[sciencedirect.com, sciencedirect.com]",2
105134,1180862642740715522,7a2af805c0921bad29a797c60226c18e,False,ahrq.gov nih.gov nationalacademies.org ssrn.co...,[],0,"[nih.gov, nih.gov, sciencedirect.com]",3
162951,1181922529142702080,346b000dbef17f4f5b3bb32a0a37d4fe,False,who.int who.int who.int who.int,[],0,"[who.int, who.int, who.int, who.int]",4

***

In [25]:
pfad_tsv3 = '../data/tweetscov19_domainsLR_science_polarized_useres.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetscov19.iterrows():
        tsv_writer.writerow(row.values.tolist())

***

In [2]:
path_tweetscov19 = '../data/tweetscov19_domainsLR_science_polarized_useres.tsv'

df_tweetscov19 = pd.read_csv(path_tweetscov19, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Antisciens_domains', 'number_of_antisciens_domains', 'Prosciens_domains', 'number_of_prosciens_domains'])

print('Shape :', df_tweetscov19.shape)
df_tweetscov19.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,number_of_antisciens_domains,Prosciens_domains,number_of_prosciens_domains
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0,0,0,0,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[],0,[],0
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0,0,0,0,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0,0,0,0,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0,0,0,0,0

In [3]:
df_tweetscov19_del = df_tweetscov19[df_tweetscov19['Is_deleted'] == True]
df_tweetscov19_undel = df_tweetscov19[df_tweetscov19['Is_deleted'] == False]

In [19]:
import ast

def get_unique_domains_with_their_number_of_repeatation(df):
    dict_domains = {}
    i  = 0

    for idx, row in df.iterrows():
        list_domains = []
        list_domains = (row.values.tolist()[0])
        
        list_domains = ast.literal_eval(list_domains)

        if (list_domains != 0):
            if (len(list_domains) > 0):
                #print(list_domains)
                for i in range(0, len(list_domains)):
                    domain = list_domains[i]
                    if domain not in dict_domains:
                        dict_domains[domain] = 1
                    else :
                        dict_domains[domain] = dict_domains[domain] +1
    return dict_domains

In [20]:
df_tweetsCov19_domains_asc = df_tweetscov19[['Antisciens_domains']]
dict_tweetscov19_domains_asc = get_unique_domains_with_their_number_of_repeatation(df_tweetsCov19_domains_asc)

In [21]:
df_dict_tweetsCov19_antiscience_domains = pd.DataFrame(dict_tweetscov19_domains_asc.items(), columns=['Antiscience_domains','Number'])
df_dict_tweetsCov19_antiscience_domains.head(1)

  Antiscience_domains  Number
0     additudemag.com      29

In [22]:
Number_of_antiscience_domains = df_tweetscov19['number_of_antisciens_domains'].sum()
print('Number of used antiscience Domains in TweetsCov19(unique) :', df_dict_tweetsCov19_antiscience_domains.Antiscience_domains.size)
print('Number of used antiscience Domains in TweetsCov19(sum) :', Number_of_antiscience_domains)

Number of used antiscience Domains in TweetsCov19(unique) : 510
Number of used antiscience Domains in TweetsCov19(sum) : 114244

In [23]:
df_dict_tweetsCov19_antiscience_domains['percent'] =  df_dict_tweetsCov19_antiscience_domains['Number'].apply(lambda row : ((row /2508542) * 100) )

df_dict_tweetsCov19_antiscience_domains['Number'] = df_dict_tweetsCov19_antiscience_domains['Number'].astype(int) 
df_dict_tweetsCov19_antiscience_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetsCov19_antiscience_domains.head(10)

     Antiscience_domains  Number   percent
1   thegatewaypundit.com   16009  0.638179
6          breitbart.com   14068  0.560804
20       dailymail.co.uk   11368  0.453172
5      theepochtimes.com    6055  0.241375
8          zerohedge.com    4723  0.188277
49        truepundit.com    4601  0.183413
27                rt.com    2873  0.114529
7    washingtontimes.com    2619  0.104403
43    westernjournal.com    2359  0.094039
45          theblaze.com    2119  0.084471

In [24]:
df_tweetsCov19_domains_psc = df_tweetscov19[['Prosciens_domains']]
dict_tweetscov19_domains_psc = get_unique_domains_with_their_number_of_repeatation(df_tweetsCov19_domains_psc)

In [25]:
df_dict_tweetsCov19_proscience_domains = pd.DataFrame(dict_tweetscov19_domains_psc.items(), columns=['Proscience_domains','Number'])

In [27]:
Number_of_proscience = df_tweetscov19['number_of_prosciens_domains'].sum()
print('Number of used proscience Domains in TweetsCov19(unique) :', df_dict_tweetsCov19_proscience_domains.Proscience_domains.size) 
print('Number of used proscience Domains in TweetsCov19(sum) :', Number_of_proscience)

Number of used proscience Domains in TweetsCov19(unique) : 121
Number of used proscience Domains in TweetsCov19(sum) : 35587

In [28]:
df_dict_tweetsCov19_proscience_domains['percent'] =  df_dict_tweetsCov19_proscience_domains['Number'].apply(lambda row : ((row /2508542) * 100) )

df_dict_tweetsCov19_proscience_domains['Number'] = df_dict_tweetsCov19_proscience_domains['Number'].astype(int) 
df_dict_tweetsCov19_proscience_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetsCov19_proscience_domains.head(10)

        Proscience_domains  Number   percent
17                 cdc.gov    6262  0.249627
6                  nih.gov    3597  0.143390
32                 who.int    2976  0.118635
3               nature.com    2724  0.108589
2            thelancet.com    1607  0.064061
10                 bmj.com    1517  0.060473
18    technologyreview.com    1386  0.055251
30                nejm.org    1137  0.045325
1        sciencedirect.com     973  0.038787
4   nationalgeographic.com     894  0.035638

----

In [4]:
path_tweetscov19 = '../data/tweetscov19_domainsLR_science_polarized_useres.tsv'

df_tweetscov19 = pd.read_csv(path_tweetscov19, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Antisciens_domains', 'number_of_antisciens_domains', 'Prosciens_domains', 'number_of_prosciens_domains'])

print('Shape :', df_tweetscov19.shape)
df_tweetscov19.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,number_of_antisciens_domains,Prosciens_domains,number_of_prosciens_domains
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0,0,0,0,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[],0,[],0
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0,0,0,0,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0,0,0,0,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0,0,0,0,0

In [5]:
cond1 = df_tweetscov19.number_of_antisciens_domains != 0
cond2 = df_tweetscov19.number_of_prosciens_domains != 0
df_tweetscov19 = df_tweetscov19[(cond1 | cond2)]

In [7]:
df_tweetscov19.number_of_antisciens_domains = df_tweetscov19.number_of_antisciens_domains *-1

In [8]:
df_tweetscov19['tweet_science_polarisation'] = df_tweetscov19.apply(lambda row: ( ((row['number_of_antisciens_domains'] + row['number_of_prosciens_domains'])) / ((row['number_of_prosciens_domains'] - row['number_of_antisciens_domains'])) if (row['number_of_prosciens_domains'] - row['number_of_antisciens_domains']) != 0 else 0), axis=1)

In [9]:
df_tweetscov19.describe()

,Tweet_Id,number_of_antisciens_domains,number_of_prosciens_domains,tweet_science_polarisation
count,1.483080e+05,148308.000000,148308.000000,148308.000000
mean,1.240849e+18,-0.770316,0.239953,-0.528931
std,2.032567e+16,0.434772,0.439137,0.848425
min,1.178792e+18,-4.000000,0.000000,-1.000000
25%,1.235905e+18,-1.000000,0.000000,-1.000000
50%,1.245437e+18,-1.000000,0.000000,-1.000000
75%,1.254745e+18,-1.000000,0.000000,-1.000000
max,1.267228e+18,0.000000,6.000000,1.000000

In [10]:
pfad_tsv3 = '../data/tweetscov19_domainsLR_science_polarized_tweets.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetscov19.iterrows():
        tsv_writer.writerow(row.values.tolist())

## Polarisierungen berechnen
### TweetsKB

***

In [26]:
pfad_tsv3 = '../data/tweetskb_id_isdeleted_domains.tsv'

df_tweetskb = pd.read_csv(pfad_tsv3, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username' ,'Is_deleted', 'Domains'])

print('Shape :', df_tweetskb.shape)
df_tweetskb.head()

Shape : (9409841, 4)

              Tweet_Id         Username  Is_deleted                 Domains
0  1178791636039589889         DCComics       False  dcuniverseinfinite.com
1  1178791641265639424       seanberdyz        True                carrd.co
2  1178791640573579264  AnArtistAtBirth        True                       0
3  1178791644797255680     lagosboygang        True                       0
4  1178791648056217600     Phenom_Hoops       False    phenomhoopreport.com

In [27]:
df_tweetskb['Domains'] = df_tweetskb['Domains'].astype(str)
df_tweetskb['Antisciens_domains'] = df_tweetskb.apply(lambda row: get_number_of_antiscience_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [28]:
df_tweetskb.head()

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains
0,1178791636039589889,DCComics,False,dcuniverseinfinite.com,[]
1,1178791641265639424,seanberdyz,True,carrd.co,[]
2,1178791640573579264,AnArtistAtBirth,True,0,0
3,1178791644797255680,lagosboygang,True,0,0
4,1178791648056217600,Phenom_Hoops,False,phenomhoopreport.com,[]

In [29]:
df_tweetskb['Number_of_antisciens_domains'] = df_tweetskb.apply(lambda row: len(row['Antisciens_domains']) if (row['Antisciens_domains'] != 0) else 0, axis=1)

In [30]:
df_tweetskb[df_tweetskb.Number_of_antisciens_domains > 1].head()

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,Number_of_antisciens_domains
51424,1179373615084720128,SotelloTV,True,dailymail.co.uk dailymail.co.uk msn.com msn.com,"[dailymail.co.uk, dailymail.co.uk]",2
495994,1184119133232865281,TomFitton,False,youtu.be foxnews.com judicialwatch.org judicia...,"[judicialwatch.org, judicialwatch.org, judicia...",3
703981,1186338695026237443,LoneGunmen63,True,globalresearch.ca globalresearch.ca,"[globalresearch.ca, globalresearch.ca]",2
875899,1188137455863685127,peta,False,peta.org peta.org,"[peta.org, peta.org]",2
907705,1188497809483403265,LarryCopling,False,newspunch.com newspunch.com,"[newspunch.com, newspunch.com]",2

In [31]:
df_tweetskb['Prosciens_domains'] = df_tweetskb.apply(lambda row: get_number_of_proscience_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [34]:
df_tweetskb['Number_of_prosciens_domains'] = df_tweetskb.apply(lambda row: len(row['Prosciens_domains']) if (row['Prosciens_domains'] != 0) else 0, axis=1)

In [35]:
df_tweetskb[df_tweetskb.Number_of_prosciens_domains > 1].head()

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,Number_of_antisciens_domains,Prosciens_domains,Number_of_prosciens_domains
199795,1180950858391019520,spaceanswers,False,livescience.com space.com,[],0,"[livescience.com, space.com]",2
722908,1186527518003740672,DegenRolf,False,nature.com nature.com,[],0,"[nature.com, nature.com]",2
980185,1189255451956916225,ChristelDepienn,False,nature.com nature.com,[],0,"[nature.com, nature.com]",2
1035191,1189826044896980992,DrTurkayYildiz,False,researchgate.net researchgate.net,[],0,"[researchgate.net, researchgate.net]",2
1074836,1190246457082695680,DukeHeitman,False,eurekalert.org plos.org,[],0,"[eurekalert.org, plos.org]",2

***

In [36]:
pfad_tsv3 = '../data/tweetskb_domainsLR_science_polarized_useres.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetskb.iterrows():
        tsv_writer.writerow(row.values.tolist())

---

In [29]:
path_tweetskb = '../data/tweetskb_domainsLR_science_polarized_useres.tsv'

df_tweetskb = pd.read_csv(path_tweetskb, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Antisciens_domains', 'number_of_antisciens_domains', 'Prosciens_domains', 'number_of_prosciens_domains'])

print('Shape :', df_tweetskb.shape)
df_tweetskb.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,number_of_antisciens_domains,Prosciens_domains,number_of_prosciens_domains
0,1178791636039589889,DCComics,False,dcuniverseinfinite.com,[],0,[],0
1,1178791641265639424,seanberdyz,True,carrd.co,[],0,[],0
2,1178791640573579264,AnArtistAtBirth,True,0,0,0,0,0
3,1178791644797255680,lagosboygang,True,0,0,0,0,0
4,1178791648056217600,Phenom_Hoops,False,phenomhoopreport.com,[],0,[],0

In [30]:
df_tweetskb_del = df_tweetskb[df_tweetskb['Is_deleted'] == True]
df_tweetskb_undel = df_tweetskb[df_tweetskb['Is_deleted'] == False]

In [31]:
df_tweetskb_domains_asc = df_tweetskb[['Antisciens_domains']]
dict_tweetskb_domains_asc = get_unique_domains_with_their_number_of_repeatation(df_tweetskb_domains_asc)

In [32]:
df_dict_tweetskb_antiscience_domains = pd.DataFrame(dict_tweetskb_domains_asc.items(), columns=['Antiscience_domains','Number'])
df_dict_tweetskb_antiscience_domains.head(1)

  Antiscience_domains  Number
0        townhall.com     578

In [33]:
Number_of_antiscience_domains = df_tweetskb['number_of_antisciens_domains'].sum()
print('Number of used antiscience Domains in TweetsCov19(unique) :', df_dict_tweetskb_antiscience_domains.Antiscience_domains.size)
print('Number of used antiscience Domains in TweetsCov19(sum) :', Number_of_antiscience_domains)

Number of used antiscience Domains in TweetsCov19(unique) : 463
Number of used antiscience Domains in TweetsCov19(sum) : 27638

In [35]:
df_dict_tweetskb_antiscience_domains['percent'] =  df_dict_tweetskb_antiscience_domains['Number'].apply(lambda row : ((row /1460380) * 100) )

df_dict_tweetskb_antiscience_domains['Number'] = df_dict_tweetskb_antiscience_domains['Number'].astype(int) 
df_dict_tweetskb_antiscience_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetskb_antiscience_domains.head(10)

     Antiscience_domains  Number   percent
9   thegatewaypundit.com    4273  0.292595
3          breitbart.com    4127  0.282598
8        dailymail.co.uk    2506  0.171599
41     theepochtimes.com    1055  0.072241
27        truepundit.com    1018  0.069708
20         zerohedge.com     967  0.066216
14                rt.com     630  0.043139
32     thefederalist.com     607  0.041565
10    westernjournal.com     593  0.040606
0           townhall.com     578  0.039579

In [36]:
df_tweetskb_domains_psc = df_tweetskb[['Prosciens_domains']]
dict_tweetskb_domains_psc = get_unique_domains_with_their_number_of_repeatation(df_tweetskb_domains_psc)

In [37]:
df_dict_tweetskb_proscience_domains = pd.DataFrame(dict_tweetskb_domains_psc.items(), columns=['Proscience_domains','Number'])

In [38]:
Number_of_proscience = df_tweetskb['number_of_prosciens_domains'].sum()
print('Number of used proscience Domains in Tweetskb(unique) :', df_dict_tweetskb_proscience_domains.Proscience_domains.size) 
print('Number of used proscience Domains in Tweetskb(sum) :', Number_of_proscience)

Number of used proscience Domains in Tweetskb(unique) : 114
Number of used proscience Domains in Tweetskb(sum) : 6733

In [39]:
df_dict_tweetskb_proscience_domains['percent'] =  df_dict_tweetskb_proscience_domains['Number'].apply(lambda row : ((row /1460380) * 100) )

df_dict_tweetskb_proscience_domains['Number'] = df_dict_tweetskb_proscience_domains['Number'].astype(int) 
df_dict_tweetskb_proscience_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetskb_proscience_domains.head(10)

        Proscience_domains  Number   percent
1                  nih.gov     692  0.047385
2               nature.com     675  0.046221
5                 nasa.gov     642  0.043961
3                  cdc.gov     404  0.027664
7                 phys.org     236  0.016160
37       sciencedirect.com     236  0.016160
41    technologyreview.com     232  0.015886
53                 who.int     229  0.015681
6                  bmj.com     166  0.011367
49  scientificamerican.com     156  0.010682

----

In [11]:
path_tweetskb = '../data/tweetskb_domainsLR_science_polarized_useres.tsv'

df_tweetskb = pd.read_csv(path_tweetskb, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Antisciens_domains', 'number_of_antisciens_domains', 'Prosciens_domains', 'number_of_prosciens_domains'])

print('Shape :', df_tweetskb.shape)
df_tweetskb.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Antisciens_domains,number_of_antisciens_domains,Prosciens_domains,number_of_prosciens_domains
0,1178791636039589889,DCComics,False,dcuniverseinfinite.com,[],0,[],0
1,1178791641265639424,seanberdyz,True,carrd.co,[],0,[],0
2,1178791640573579264,AnArtistAtBirth,True,0,0,0,0,0
3,1178791644797255680,lagosboygang,True,0,0,0,0,0
4,1178791648056217600,Phenom_Hoops,False,phenomhoopreport.com,[],0,[],0

In [12]:
cond1 = df_tweetskb.number_of_antisciens_domains != 0
cond2 = df_tweetskb.number_of_prosciens_domains != 0
df_tweetskb = df_tweetskb[(cond1 | cond2)]

In [13]:
df_tweetskb.number_of_antisciens_domains = df_tweetskb.number_of_antisciens_domains *-1

In [14]:
df_tweetskb['tweet_science_polarisation'] = df_tweetskb.apply(lambda row: ( ((row['number_of_antisciens_domains'] + row['number_of_prosciens_domains'])) / ((row['number_of_prosciens_domains'] - row['number_of_antisciens_domains'])) if (row['number_of_prosciens_domains'] - row['number_of_antisciens_domains']) != 0 else 0), axis=1)

In [15]:
df_tweetskb.describe()

,Tweet_Id,number_of_antisciens_domains,number_of_prosciens_domains,tweet_science_polarisation
count,3.408100e+04,34081.00000,34081.000000,34081.000000
mean,1.224598e+18,-0.81095,0.197559,-0.612775
std,2.582571e+16,0.40518,0.411856,0.790250
min,1.178760e+18,-6.00000,0.000000,-1.000000
25%,1.201944e+18,-1.00000,0.000000,-1.000000
50%,1.225654e+18,-1.00000,0.000000,-1.000000
75%,1.247534e+18,-1.00000,0.000000,-1.000000
max,1.267207e+18,0.00000,8.000000,1.000000

In [16]:
pfad_tsv3 = '../data/tweetskb_domainsLR_science_polarized_tweets.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetskb.iterrows():
        tsv_writer.writerow(row.values.tolist())