In [1]:
#Import CSV Bibliothek 
import csv
#Import Pandas and label it as pd
import pandas as pd
#Import numpy and label it as np 
import numpy as np
#Import Json library
import json
#Set size of Data on 100,000,000 line  
csv.field_size_limit(100000000)
#Display max. rows and columns 
pd.options.display.max_columns = None
pd.options.display.max_rows = None
#Import tldextract for extraction of Domains
import tldextract
#Show warnings just in console 
import warnings
warnings.filterwarnings('ignore')

***

# Political Polarisiation

### Liberale domais

***

In [2]:
path = '../data/df_domains_left_right.tsv'

df_liberal_conservative_domains = pd.read_csv(path, sep='\t', error_bad_lines=False)

In [3]:
print('Shape: ', df_liberal_conservative_domains.shape)
df_liberal_conservative_domains.head()

Shape:  (1589, 5)

,domain,mediabias_leftcenterbias,mediabias_leftbias,mediabias_rightcenterbias,mediabias_rightbias
0,604now.com,1.0,0.0,0.0,0.0
1,972mag.com,1.0,0.0,0.0,0.0
2,Augustachronicle.com,1.0,0.0,0.0,0.0
3,Boston.com,1.0,0.0,0.0,0.0
4,Censor.NET,1.0,0.0,0.0,0.0

In [4]:
df_leftcenterbias = df_liberal_conservative_domains[df_liberal_conservative_domains['mediabias_leftcenterbias'] == 1]

print('Shape: ', df_leftcenterbias.shape)
df_leftcenterbias.head()

Shape:  (644, 5)

,domain,mediabias_leftcenterbias,mediabias_leftbias,mediabias_rightcenterbias,mediabias_rightbias
0,604now.com,1.0,0.0,0.0,0.0
1,972mag.com,1.0,0.0,0.0,0.0
2,Augustachronicle.com,1.0,0.0,0.0,0.0
3,Boston.com,1.0,0.0,0.0,0.0
4,Censor.NET,1.0,0.0,0.0,0.0

In [5]:
list_leftcenterbias_domains = df_leftcenterbias.domain.tolist()

In [6]:
def get_unique_items(list_1):
    
    list_1 = np.array(list_1)
    list_1 = np.unique(list_1)
    list_1 = list_1.tolist()
    
    return list_1

In [7]:
list_leftcenterbias_domains = get_unique_items(list_leftcenterbias_domains)
len(list_leftcenterbias_domains)

644

In [8]:
df_leftbias = df_liberal_conservative_domains[df_liberal_conservative_domains['mediabias_leftbias'] == 1]

print('Shape: ', df_leftbias.shape)
df_leftbias.head()

Shape:  (310, 5)

,domain,mediabias_leftcenterbias,mediabias_leftbias,mediabias_rightcenterbias,mediabias_rightbias
644,19thnews.org,0.0,1.0,0.0,0.0
645,Accountable.US,0.0,1.0,0.0,0.0
646,Brut.Media,0.0,1.0,0.0,0.0
647,JoeBiden.com,0.0,1.0,0.0,0.0
648,Them.us,0.0,1.0,0.0,0.0

In [9]:
list_leftbias_domains = df_leftbias.domain.tolist()

In [10]:
list_leftbias_domains = get_unique_items(list_leftbias_domains)
len(list_leftbias_domains)

310

In [11]:
list_liberal_domains = []

list_liberal_domains.extend(list_leftbias_domains)
list_liberal_domains.extend(list_leftcenterbias_domains)

list_liberal_domains = get_unique_items(list_liberal_domains)
len(list_liberal_domains)

954

***

## Conservative Domains

***

In [12]:
df_rightcenterbias = df_liberal_conservative_domains[df_liberal_conservative_domains['mediabias_rightcenterbias'] == 1]

print('Shape: ', df_rightcenterbias.shape)
df_rightcenterbias.head()

Shape:  (381, 5)

,domain,mediabias_leftcenterbias,mediabias_leftbias,mediabias_rightcenterbias,mediabias_rightbias
954,13wham.com,0.0,0.0,1.0,0.0
955,19fortyfive.com,0.0,0.0,1.0,0.0
956,7news.com.au,0.0,0.0,1.0,0.0
957,9news.com.au,0.0,0.0,1.0,0.0
958,Deutschland.de,0.0,0.0,1.0,0.0

In [13]:
list_rightcenterbias_domains = df_rightcenterbias.domain.tolist()

list_rightcenterbias_domains = get_unique_items(list_rightcenterbias_domains)
len(list_rightcenterbias_domains)

381

In [14]:
df_rightbias = df_liberal_conservative_domains[df_liberal_conservative_domains['mediabias_rightbias'] == 1]

print('Shape: ', df_rightbias.shape)
df_rightbias.head()

Shape:  (254, 5)

,domain,mediabias_leftcenterbias,mediabias_leftbias,mediabias_rightcenterbias,mediabias_rightbias
1335,2ndvote.com,0.0,0.0,0.0,1.0
1336,Abort73.com,0.0,0.0,0.0,1.0
1337,Aish.com,0.0,0.0,0.0,1.0
1338,AsianNews.it,0.0,0.0,0.0,1.0
1339,CAGW.org,0.0,0.0,0.0,1.0

In [15]:
list_rightbias_domains = df_rightbias.domain.tolist()

list_rightbias_domains = get_unique_items(list_rightbias_domains)
len(list_rightbias_domains)

254

In [16]:
list_conservative_domains = []

list_conservative_domains.extend(list_rightbias_domains)
list_conservative_domains.extend(list_rightcenterbias_domains)

list_conservative_domains = get_unique_items(list_conservative_domains)
len(list_conservative_domains)

635

***

## TweetsCov19

In [17]:
path_tweetscov19 = '../data/tweetscov19_id_isdeleted_domains.tsv'

df_tweetscov19 = pd.read_csv(path_tweetscov19, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains'])

print('Shape :', df_tweetscov19.shape)
df_tweetscov19.head()

Shape : (9409841, 4)

,Tweet_Id,Username,Is_deleted,Domains
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0

In [18]:
def get_number_of_liberal_domains(domains):
    
    domains_list = domains.split()
    score = 0
    l = []
    for i in range(0, len(domains_list)):
        
        #d = tldextract.extract(domains_list[i])
        #d = d.domain
        d = domains_list[i]
        
        if d in list_liberal_domains:
            score -=  1
            l.append(d)
    return l

In [19]:
df_tweetscov19['Domains'] = df_tweetscov19['Domains'].astype(str)

df_tweetscov19['Liberal_domains'] = df_tweetscov19.apply(lambda row: get_number_of_liberal_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [30]:
df_tweetscov19[df_tweetscov19['Domains']!= '0'].head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[],0
5,1178791653152194560,0b79ffbeab9f663eb505761a40b76241,False,twittascope.com,[],0
7,1178791661574316032,def24719cfa92fcba6de9ae9147293df,False,twitter.com google.com,[],0
8,1178791665760423937,5318a0819dfce491407d54c8bf6fcc96,False,airtime.pro,[],0
11,1178791665760268291,234052147f4eb61d347c8bb8d29a51b7,False,bit.ly,[],0

In [25]:
df_tweetscov19['Number_of_liberals'] = df_tweetscov19.apply(lambda row: len(row['Liberal_domains']) if (row['Liberal_domains'] != 0) else 0, axis=1)

In [28]:
df_tweetscov19[df_tweetscov19.Number_of_liberals >1].head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals
2878,1178845541461057536,2435a45b85628172c5a47122144a7c67,False,cnn.com cnn.com,"[cnn.com, cnn.com]",2
4726,1178882401122050048,d42173071607f0bbce9d86ed25fc85b5,False,medium.com medium.com medium.com,"[medium.com, medium.com, medium.com]",3
11005,1179022210310299649,628f78c70516c829d81bdef58a8ec4e0,False,latimes.com latimes.com,"[latimes.com, latimes.com]",2
11238,1179025758234255362,734012e71d6e9ff93ac0e7dc83dba31a,True,thenation.com globaltimes.cn,"[thenation.com, globaltimes.cn]",2
14228,1179067849769308160,1ebd59e1442eff260eb058d861064f48,False,washingtonpost.com senate.gov theatlantic.com,"[washingtonpost.com, theatlantic.com]",2

In [31]:
def get_number_of_conservative_domains(domains):
    domains_list = domains.split()
    score = 0
    l = []
    for i in range(0, len(domains_list)):
        
        #d = tldextract.extract(domains_list[i])
        #d = d.domain
        d =  domains_list[i]
        
        if d in list_conservative_domains:
            score +=  1
            l.append(d)
    return l

In [32]:
df_tweetscov19['Conservative_domains'] = df_tweetscov19.apply(lambda row: get_number_of_conservative_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [33]:
df_tweetscov19.head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0,0,0,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[],0,[]
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0,0,0,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0,0,0,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0,0,0,0

In [36]:
df_tweetscov19['Number_of_conservatives'] = df_tweetscov19.apply(lambda row: len(row['Conservative_domains']) if (row['Conservative_domains'] != 0) else 0, axis=1)

In [39]:
df_tweetscov19[df_tweetscov19.Number_of_conservatives > 1].head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservatives
42516,1179612960806838272,36a2270f35ac1a16d7bd9661f9fcdf4b,False,washingtonexaminer.com nypost.com,[],0,"[washingtonexaminer.com, nypost.com]",2
50900,1179790547814424577,abba72da77420cc47068961d732d2043,True,washingtonexaminer.com nypost.com,[],0,"[washingtonexaminer.com, nypost.com]",2
88139,1180491763900977157,55b8a45ae990c0e6bd9e01462317c7cf,False,nypost.com nypost.com,[],0,"[nypost.com, nypost.com]",2
137864,1181464091703087109,9be07e39a3a6157972e1435c30054de2,False,foxbusiness.com foxnews.com,[],0,"[foxbusiness.com, foxnews.com]",2
154684,1181739317733056512,9a03cb041ffb42baf9854b27decfdc61,True,twitchy.com twitchy.com,[],0,"[twitchy.com, twitchy.com]",2

***

In [40]:
pfad_tsv3 = '../data/tweetscov19_domainsLR_political_polarized_useres.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetscov19.iterrows():
        tsv_writer.writerow(row.values.tolist())

****

In [2]:
path_tweetscov19 = '../data/tweetscov19_domainsLR_political_polarized_useres.tsv'

df_tweetscov19 = pd.read_csv(path_tweetscov19, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Liberal_domains', 'Number_of_liberals', 'Conservative_domains', 'Number_of_conservatives'])

print('Shape :', df_tweetscov19.shape)
df_tweetscov19.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservatives
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0,0,0,0,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[],0,[],0
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0,0,0,0,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0,0,0,0,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0,0,0,0,0

In [3]:
df_tweetscov19_del = df_tweetscov19[df_tweetscov19['Is_deleted'] == True]
df_tweetscov19_undel = df_tweetscov19[df_tweetscov19['Is_deleted'] == False]

In [4]:
import ast

def get_unique_domains_with_their_number_of_repeatation(df):
    dict_domains = {}
    i  = 0

    for idx, row in df.iterrows():
        list_domains = []
        list_domains = (row.values.tolist()[0])
        
        list_domains = ast.literal_eval(list_domains)

        if (list_domains != 0):
            if (len(list_domains) > 0):
                #print(list_domains)
                for i in range(0, len(list_domains)):
                    domain = list_domains[i]
                    if domain not in dict_domains:
                        dict_domains[domain] = 1
                    else :
                        dict_domains[domain] = dict_domains[domain] +1
    return dict_domains

In [5]:
df_tweetsCov19_domains_l = df_tweetscov19[['Liberal_domains']]
dict_tweetscov19_domains_l = get_unique_domains_with_their_number_of_repeatation(df_tweetsCov19_domains_l)

In [6]:
df_dict_tweetsCov19_liberal_domains = pd.DataFrame(dict_tweetscov19_domains_l.items(), columns=['liberal_domains','Number'])
df_dict_tweetsCov19_liberal_domains.head(1)

  liberal_domains  Number
0     nytimes.com   35661

In [7]:
Number_of_liberal_domains = df_tweetscov19['Number_of_liberals'].sum()
print('Number of used liberal Domains in TweetsCov19(unique) :', df_dict_tweetsCov19_liberal_domains.liberal_domains.size) #-1 is label 0 for no Domains
print('Number of used liberal Domains in TweetsCov19(sum) :', Number_of_liberal_domains)

Number of used liberal Domains in TweetsCov19(unique) : 792
Number of used liberal Domains in TweetsCov19(sum) : 472953

In [10]:
df_dict_tweetsCov19_liberal_domains['percent'] =  df_dict_tweetsCov19_liberal_domains['Number'].apply(lambda row : ((row /2508542) * 100) )

df_dict_tweetsCov19_liberal_domains['Number'] = df_dict_tweetsCov19_liberal_domains['Number'].astype(int) 
df_dict_tweetsCov19_liberal_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetsCov19_liberal_domains.head(10)

       liberal_domains  Number   percent
0          nytimes.com   35661  1.421583
12     theguardian.com   33863  1.349908
1              cnn.com   29895  1.191728
5   washingtonpost.com   25083  0.999904
11       bloomberg.com   16885  0.673100
4         rawstory.com   11516  0.459071
24         nbcnews.com   11190  0.446076
13            cnbc.com    9763  0.389190
7              bbc.com    9180  0.365950
85   independent.co.uk    8907  0.355067

In [35]:
df_tweetsCov19_domains_c = df_tweetscov19[['Conservative_domains']]
dict_tweetscov19_domains_c = get_unique_domains_with_their_number_of_repeatation(df_tweetsCov19_domains_c)

In [36]:
df_dict_tweetsCov19_conservative_domains = pd.DataFrame(dict_tweetscov19_domains_c.items(), columns=['Conservative_domains','Number'])

In [37]:
Number_of_conservatives = df_tweetscov19['Number_of_conservatives'].sum()
print('Number of used conservative Domains in TweetsCov19(unique) :', df_dict_tweetsCov19_conservative_domains.Conservative_domains.size) #-1 is label 0 for no Domains
print('Number of used conservative Domains in TweetsCov19(sum) :', Number_of_conservatives)

Number of used conservative Domains in TweetsCov19(unique) : 489
Number of used conservative Domains in TweetsCov19(sum) : 141237

In [39]:
df_dict_tweetsCov19_conservative_domains['percent'] =  df_dict_tweetsCov19_conservative_domains['Number'].apply(lambda row : ((row /2508542) * 100) )

df_dict_tweetsCov19_conservative_domains['Number'] = df_dict_tweetsCov19_conservative_domains['Number'].astype(int) 
df_dict_tweetsCov19_conservative_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetsCov19_conservative_domains.head(10)

      Conservative_domains  Number   percent
2              foxnews.com   18794  0.749200
5               nypost.com    9192  0.366428
24                 wsj.com    8582  0.342111
28          indiatimes.com    7302  0.291085
0               forbes.com    7021  0.279884
35         telegraph.co.uk    4624  0.184330
9   washingtonexaminer.com    4544  0.181141
14         dailycaller.com    3981  0.158698
10           dailywire.com    2495  0.099460
7           thetimes.co.uk    2428  0.096789

In [55]:
path_tweetscov19 = '../data/tweetscov19_domainsLR_political_polarized_useres.tsv'

df_tweetscov19 = pd.read_csv(path_tweetscov19, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Liberal_domains', 'Number_of_liberals', 'Conservative_domains', 'Number_of_conservatives'])

print('Shape :', df_tweetscov19.shape)
df_tweetscov19.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservatives
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,True,0,0,0,0,0
1,1178791641601232896,627f7d4ef584ba33a676a4ebcb861cdb,False,catholicnewsagency.com,[],0,[],0
2,1178791643509612547,7966d5716c1c4f33591b17755184e3d6,False,0,0,0,0,0
3,1178791644214235137,f17996c036ed4cd981f5448fe00d9ed2,False,0,0,0,0,0
4,1178791645371875329,32a54e5f6d8a67de1bffd2e689594dc8,False,0,0,0,0,0

In [57]:
cond1 = df_tweetscov19.Number_of_liberals != 0
cond2 = df_tweetscov19.Number_of_conservatives != 0
df_tweetscov19 = df_tweetscov19[(cond1 | cond2)]

In [58]:
df_tweetscov19.Number_of_liberals = df_tweetscov19.Number_of_liberals *-1

In [60]:
df_tweetscov19['tweet_political_polarisation'] = df_tweetscov19.apply(lambda row: ( ((row['Number_of_liberals'] + row['Number_of_conservatives']) / (row['Number_of_conservatives'] - row['Number_of_liberals'])) if (row['Number_of_conservatives'] - row['Number_of_liberals']) != 0 else 0), axis=1)

In [61]:
df_tweetscov19.describe()

,Tweet_Id,Number_of_liberals,Number_of_conservatives,tweet_political_polarisation
count,6.118350e+05,611835.000000,611835.000000,611835.000000
mean,1.241852e+18,-0.773007,0.230842,-0.540216
std,1.907819e+16,0.426716,0.423492,0.841310
min,1.178792e+18,-6.000000,0.000000,-1.000000
25%,1.238215e+18,-1.000000,0.000000,-1.000000
50%,1.245422e+18,-1.000000,0.000000,-1.000000
75%,1.254079e+18,-1.000000,0.000000,-1.000000
max,1.267229e+18,0.000000,7.000000,1.000000

In [63]:
df_tweetscov19[df_tweetscov19.tweet_political_polarisation < 0 ].head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservatives,tweet_political_polarisation
14,1178791675315011589,29fc6f98710433e0e0cada38c8c4802a,False,nytimes.com,['nytimes.com'],-1,[],0,-1.0
20,1178791745447968768,c940ede6cf28e2e8d18603673ae6f637,True,cnn.com,['cnn.com'],-1,[],0,-1.0
30,1178791856890503170,75de0fdf8252dd62490c90d82566e1fa,False,mercurynews.com,['mercurynews.com'],-1,[],0,-1.0
36,1178791939728130048,f519630366630cbb2b0cdb4aed83d604,False,theatlantic.com,['theatlantic.com'],-1,[],0,-1.0
37,1178791946413846529,d0f73e6d57bde75aae4136a37e41a388,False,rawstory.com,['rawstory.com'],-1,[],0,-1.0

In [64]:
pfad_tsv3 = '../data/tweetscov19_domainsLR_political_polarized_tweets.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetscov19.iterrows():
        tsv_writer.writerow(row.values.tolist())

## Polarisierungen berechnen
### TweetsKB

***

In [41]:
pfad_tsv = '../data/tweetskb_id_isdeleted_domains.tsv'

df_tweetskb = pd.read_csv(pfad_tsv, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains'])

print('Shape :', df_tweetskb.shape)
df_tweetskb.head()

Shape : (9409841, 4)

              Tweet_Id         Username  Is_deleted                 Domains
0  1178791636039589889         DCComics       False  dcuniverseinfinite.com
1  1178791641265639424       seanberdyz        True                carrd.co
2  1178791640573579264  AnArtistAtBirth        True                       0
3  1178791644797255680     lagosboygang        True                       0
4  1178791648056217600     Phenom_Hoops       False    phenomhoopreport.com

In [42]:
df_tweetskb['Domains'] = df_tweetskb['Domains'].astype(str)

df_tweetskb['Liberal_domains'] = df_tweetskb.apply(lambda row: get_number_of_liberal_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [43]:
df_tweetskb.head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains
0,1178791636039589889,DCComics,False,dcuniverseinfinite.com,[]
1,1178791641265639424,seanberdyz,True,carrd.co,[]
2,1178791640573579264,AnArtistAtBirth,True,0,0
3,1178791644797255680,lagosboygang,True,0,0
4,1178791648056217600,Phenom_Hoops,False,phenomhoopreport.com,[]

In [44]:
df_tweetskb['Number_of_liberals'] = df_tweetskb.apply(lambda row: len(row['Liberal_domains']) if (row['Liberal_domains'] != 0) else 0, axis=1)

In [46]:
df_tweetskb[df_tweetskb.Number_of_liberals >1].head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals
22393,1179046201271967745,Historian_Matt,False,cbc.ca cbc.ca,"[cbc.ca, cbc.ca]",2
48811,1179343794896027648,superscriber,False,theguardian.com smh.com.au,"[theguardian.com, smh.com.au]",2
51424,1179373615084720128,SotelloTV,True,dailymail.co.uk dailymail.co.uk msn.com msn.com,"[msn.com, msn.com]",2
89720,1179767830855782402,PreetBharara,False,brennancenter.org nytimes.com,"[brennancenter.org, nytimes.com]",2
90651,1179774793828073472,CalPolicy,False,nytimes.com nytimes.com youtube.com,"[nytimes.com, nytimes.com]",2

In [47]:
df_tweetskb['Conservative_domains'] = df_tweetskb.apply(lambda row: get_number_of_conservative_domains(row['Domains']) if (row['Domains'] != '0') else 0, axis=1)

In [48]:
df_tweetskb.head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains
0,1178791636039589889,DCComics,False,dcuniverseinfinite.com,[],0,[]
1,1178791641265639424,seanberdyz,True,carrd.co,[],0,[]
2,1178791640573579264,AnArtistAtBirth,True,0,0,0,0
3,1178791644797255680,lagosboygang,True,0,0,0,0
4,1178791648056217600,Phenom_Hoops,False,phenomhoopreport.com,[],0,[]

In [50]:
df_tweetskb['Number_of_conservative'] = df_tweetskb.apply(lambda row: len(row['Conservative_domains']) if (row['Conservative_domains'] != 0) else 0, axis=1)

In [51]:
df_tweetskb[df_tweetskb.Number_of_conservative >1].head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservative
122040,1180107335018192896,DeplorableNYC50,False,foxnews.com foxnews.com,[],0,"[foxnews.com, foxnews.com]",2
139289,1180262150436089856,staronline,False,thestar.com.my thestar.com.my,[],0,"[thestar.com.my, thestar.com.my]",2
143921,1180313321481748480,tax_will,False,redstate.com redstate.com redstate.com,[],0,"[redstate.com, redstate.com, redstate.com]",3
146927,1180353477744222208,MyDesert,True,desertsun.com desertsun.com,[],0,"[desertsun.com, desertsun.com]",2
227927,1181263654320082946,LisaRowsell1,False,idahostatejournal.com idahostatejournal.com,[],0,"[idahostatejournal.com, idahostatejournal.com]",2

***

In [52]:
pfad_tsv3 = '../data/tweetskb_domainsLR_political_polarized_useres.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetskb.iterrows():
        tsv_writer.writerow(row.values.tolist())

----

In [3]:
pfad = '../data/tweetskb_domainsLR_political_polarized_useres.tsv'

df_tweetskb = pd.read_csv(pfad, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Liberal_domains', 'Number_of_liberals', 'Conservative_domains', 'Number_of_conservatives'])

print('Shape :', df_tweetskb.shape)
df_tweetskb.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservatives
0,1178791636039589889,DCComics,False,dcuniverseinfinite.com,[],0,[],0
1,1178791641265639424,seanberdyz,True,carrd.co,[],0,[],0
2,1178791640573579264,AnArtistAtBirth,True,0,0,0,0,0
3,1178791644797255680,lagosboygang,True,0,0,0,0,0
4,1178791648056217600,Phenom_Hoops,False,phenomhoopreport.com,[],0,[],0

In [4]:
df_tweetskb_del = df_tweetskb[df_tweetskb['Is_deleted'] == True]
df_tweetskb_undel = df_tweetskb[df_tweetskb['Is_deleted'] == False]

In [5]:
df_tweetskb_domains_l = df_tweetskb[['Liberal_domains']]
dict_tweetskb_domains_l = get_unique_domains_with_their_number_of_repeatation(df_tweetskb_domains_l)

In [11]:
df_dict_tweetskb_liberal_domains = pd.DataFrame(dict_tweetskb_domains_l.items(), columns=['liberal_domains','Number'])
df_dict_tweetskb_liberal_domains.head()

      liberal_domains  Number
0             ajc.com     226
1             msn.com    1771
2        rawstory.com    2502
3  washingtonpost.com    4765
4        wonkette.com      58

In [12]:
Number_of_liberal_domains = df_tweetskb['Number_of_liberals'].sum()
print('Number of used liberal Domains in Tweetskb(unique) :', df_dict_tweetskb_liberal_domains.liberal_domains.size) #-1 is label 0 for no Domains
print('Number of used liberal Domains in Tweetskb(sum) :', Number_of_liberal_domains)

Number of used liberal Domains in Tweetskb(unique) : 760
Number of used liberal Domains in Tweetskb(sum) : 101104

In [14]:
df_dict_tweetskb_liberal_domains['percent'] =  df_dict_tweetskb_liberal_domains['Number'].apply(lambda row : ((row /1460380) * 100) )

df_dict_tweetskb_liberal_domains['Number'] = df_dict_tweetskb_liberal_domains['Number'].astype(int) 
df_dict_tweetskb_liberal_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetskb_liberal_domains.head(10)

       liberal_domains  Number   percent
21     theguardian.com    8832  0.604774
30         nytimes.com    5532  0.378806
3   washingtonpost.com    4765  0.326285
12             cnn.com    3680  0.251989
13          medium.com    3228  0.221038
22       bloomberg.com    2578  0.176529
2         rawstory.com    2502  0.171325
73   independent.co.uk    2219  0.151947
1              msn.com    1771  0.121270
9          nbcnews.com    1701  0.116477

In [15]:
df_tweetskb_domains_c = df_tweetskb[['Conservative_domains']]
dict_tweetskb_domains_c = get_unique_domains_with_their_number_of_repeatation(df_tweetskb_domains_c)

In [16]:
df_dict_tweetskb_conservative_domains = pd.DataFrame(dict_tweetskb_domains_c.items(), columns=['Conservative_domains','Number'])

In [17]:
Number_of_conservatives = df_tweetskb['Number_of_conservatives'].sum()
print('Number of used conservative Domains in Tweetskb(unique) :', df_dict_tweetskb_conservative_domains.Conservative_domains.size -1) #-1 is label 0 for no Domains
print('Number of used conservative Domains in Tweetskb(sum) :', Number_of_conservatives)

Number of used conservative Domains in Tweetskb(unique) : 459
Number of used conservative Domains in Tweetskb(sum) : 33349

In [21]:
df_dict_tweetskb_conservative_domains['percent'] =  df_dict_tweetskb_conservative_domains['Number'].apply(lambda row : ((row /1460380) * 100) )

df_dict_tweetskb_conservative_domains['Number'] = df_dict_tweetskb_conservative_domains['Number'].astype(int) 
df_dict_tweetskb_conservative_domains.sort_values(by = ['Number'], ascending = False, inplace = True)
df_dict_tweetskb_conservative_domains.head(10)

   Conservative_domains  Number   percent
2           foxnews.com    3720  0.254728
26           forbes.com    2001  0.137019
17           nypost.com    1862  0.127501
6               wsj.com    1619  0.110862
10       indiatimes.com    1317  0.090182
40      telegraph.co.uk    1172  0.080253
16      dailycaller.com    1073  0.073474
31       thetimes.co.uk     797  0.054575
18        dailywire.com     713  0.048823
22         thesun.co.uk     673  0.046084

****

In [78]:
pfad = '../data/tweetskb_domainsLR_political_polarized_useres.tsv'

df_tweetskb = pd.read_csv(pfad, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Is_deleted', 'Domains', 'Liberal_domains', 'Number_of_liberals', 'Conservative_domains', 'Number_of_conservatives'])

print('Shape :', df_tweetskb.shape)
df_tweetskb.head()

Shape : (9409841, 8)

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservatives
0,1178791636039589889,DCComics,False,dcuniverseinfinite.com,[],0,[],0
1,1178791641265639424,seanberdyz,True,carrd.co,[],0,[],0
2,1178791640573579264,AnArtistAtBirth,True,0,0,0,0,0
3,1178791644797255680,lagosboygang,True,0,0,0,0,0
4,1178791648056217600,Phenom_Hoops,False,phenomhoopreport.com,[],0,[],0

In [79]:
cond1 = df_tweetskb.Number_of_liberals != 0
cond2 = df_tweetskb.Number_of_conservatives != 0
df_tweetskb = df_tweetskb[(cond1 | cond2)]

In [80]:
df_tweetskb.Number_of_liberals = df_tweetskb.Number_of_liberals *-1

In [81]:
df_tweetskb['tweet_political_polarisation'] = df_tweetskb.apply(lambda row: ( ((row['Number_of_liberals'] + row['Number_of_conservatives']) / (row['Number_of_conservatives'] - row['Number_of_liberals'])) if (row['Number_of_conservatives'] - row['Number_of_liberals']) != 0 else 0), axis=1)

In [82]:
df_tweetskb[df_tweetskb.tweet_political_polarisation < 0].head()

,Tweet_Id,Username,Is_deleted,Domains,Liberal_domains,Number_of_liberals,Conservative_domains,Number_of_conservatives,tweet_political_polarisation
123,1178792740664102913,ajc,False,ajc.com,['ajc.com'],-1,[],0,-1.0
162,1178793142134292481,JuanchoS,False,msn.com,['msn.com'],-1,[],0,-1.0
217,1178793578350497806,MichaeDemitre,False,rawstory.com,['rawstory.com'],-1,[],0,-1.0
308,1178794438195212289,VIKBataille,False,msn.com,['msn.com'],-1,[],0,-1.0
319,1178794524778385408,JbarGarden,False,washingtonpost.com,['washingtonpost.com'],-1,[],0,-1.0

In [85]:
df_tweetskb.describe()

,Tweet_Id,Number_of_liberals,Number_of_conservatives,tweet_political_polarisation
count,1.336760e+05,133676.000000,133676.000000,133676.000000
mean,1.224523e+18,-0.756336,0.249476,-0.504840
std,2.582551e+16,0.439744,0.437098,0.862995
min,1.178756e+18,-5.000000,0.000000,-1.000000
25%,1.201884e+18,-1.000000,0.000000,-1.000000
50%,1.225821e+18,-1.000000,0.000000,-1.000000
75%,1.247016e+18,-1.000000,0.000000,-1.000000
max,1.267214e+18,0.000000,6.000000,1.000000

In [84]:
pfad_tsv3 = '../data/tweetskb_domainsLR_political_polarized_tweets.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetskb.iterrows():
        tsv_writer.writerow(row.values.tolist())