In [1]:
#Import CSV Bibliothek 
import csv
#Import Pandas and label it as pd
import pandas as pd
#Import numpy and label it as np 
import numpy as np
#Import Json library
import json
#Set size of Data on 100,000,000 line  
csv.field_size_limit(100000000)
#Display max. rows and columns 
pd.options.display.max_columns = None
pd.options.display.max_rows = None
#Import tldextract for extraction of Domains
import tldextract
#Show warnings just in console 
import warnings
warnings.filterwarnings('ignore')

***

# TweetsCov19

***

In [4]:
#Die Dataframe, die die Benutzer mit politischen Meinungen enth√§lt, wird hier gelesen. 
pfad_tsv = '../../tweetsCov19_user_dom_politic_2.tsv'

df_tweetscov19_politik = pd.read_csv(pfad_tsv, sep='\t', error_bad_lines=False, names=['Username', 'Urls_num', 'neg', 'pos', 'pol_dom_num', 'politic'])
pd.options.display.max_columns = None
print('Shape :', df_tweetscov19_politik.shape)
df_tweetscov19_politik.head()

Shape : (50852, 6)

   Username  Urls_num  neg  pos  pol_dom_num  politic
0       1.0      -1.0  0.0  1.0         -1.0      NaN
1       1.0      -1.0  0.0  1.0         -1.0      NaN
2       1.0      -1.0  0.0  1.0         -1.0      NaN
3       1.0      -1.0  0.0  1.0         -1.0      NaN
4       2.0      -2.0  0.0  2.0         -1.0      NaN

In [ ]:
pfad_tsv = '../../tweetsCov19_user_dom_politic_2.tsv'

df_tweetscov19_politik = pd.read_csv(pfad_tsv, sep='\t', error_bad_lines=False, names=['Username', 'Urls_num', 'neg', 'pos', 'pol_dom_num', 'politic'])
pd.options.display.max_columns = None
print('Shape :', df_tweetscov19_politik.shape)
df_tweetscov19_politik.head()

In [9]:
#Die gewonnenen Benutzer werden gespeichert.
pfad_tsv3 = 'C:/Mo/tweetDB/tweetscov19/TweetsCov19_tsv/data_sample/TweetsCov19_sample/Users/tweetscov19_user_polarisiert_1.tsv'

with open(pfad_tsv3, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetscov19_user.iterrows():
        tsv_writer.writerow(row.values.tolist())

***

In [5]:
#Hier wird die Dataframe gelesen, die die Anzahl der geposteten und gel√∂schten Tweets, L√∂schungsquote und Reputation von Benutzer enth√§lt.
 
pfad_tsv = 'C:/Mo/hhu/hhu_ba/tweetDB/tweetscov19/TweetsCov19_tsv/data_sample/TweetsCov19_sample/TweetsCov19_alle_geloeschten/TweetsCov19_all_repu_del_.tsv'

df_tweetscov19_user_repu_del = pd.read_csv(pfad_tsv, sep='\t', error_bad_lines=False, names=['Tweet_Id', 'Username', 'Followers', 'Friends', 'is_deleted', 'Reputation', 'num_posted', 'num_del', 'Deletion_ratio'])
pd.options.display.max_columns = None
print('Form :', df_tweetscov19_user_repu_del.shape)
df_tweetscov19_user_repu_del.head()

Form : (9409841, 9)

,Tweet_Id,Username,Followers,Friends,is_deleted,Reputation,num_posted,num_del,Deletion_ratio
0,1178791637348212736,c57d4fb895c5f4a33d2a2b24709f93b5,764191,132,True,0.999827,21,21,1.0
1,1181705842275573766,c57d4fb895c5f4a33d2a2b24709f93b5,765034,132,True,0.999827,21,21,1.0
2,1187828746503540738,c57d4fb895c5f4a33d2a2b24709f93b5,766578,132,True,0.999827,21,21,1.0
3,1192622772658290688,c57d4fb895c5f4a33d2a2b24709f93b5,767939,133,True,0.999827,21,21,1.0
4,1193272068621717504,c57d4fb895c5f4a33d2a2b24709f93b5,768180,133,True,0.999827,21,21,1.0

In [4]:
#die Features: Anzahl der geposteten und gel√∂schten Tweets, L√∂schungsquote und Reputation werden zu der Benutzer mit drei Polarisierungswerten hinzugef√ºgt.
df_tweetscov19_user_repu_del = df_tweetscov19_user_repu_del[['Username', 'num_posted', 'num_del', 'Deletion_ratio', 'Reputation', 'is_deleted']]
df_tweetscov19_user = pd.merge(df_tweetscov19_politik, df_tweetscov19_user_repu_del, on='Username', how='inner')
print('Form :', df_tweetscov19_user.shape)
df_tweetscov19_user.head()

Form : (2026196, 11)

,Username,Urls_num,neg,pos,pol_dom_num,politic,num_posted,num_del,Deletion_ratio,Reputation,is_deleted
0,00008ca06f863b962f72cc9167d7978a,1,-1,0,1,-1.0,1,0,0.0,0.182843,False
1,00008de3f61d5f04329ee6867d5475b9,1,-1,0,1,-1.0,1,1,1.0,0.600266,True
2,00012a177385cd6e7590e2acb3f206e3,1,-1,0,1,-1.0,2,2,1.0,0.332750,True
3,00012a177385cd6e7590e2acb3f206e3,1,-1,0,1,-1.0,2,2,1.0,0.332750,True
4,00016e20a3865cb74581803c27d27b89,1,-1,0,1,-1.0,2,0,0.0,0.589633,False

In [5]:
#Das Ergebniss wird gespeichert.
pfad_tsv = '../tweetsCov19_user_dom_politik_deletionratio_reputation.tsv'

with open(pfad_tsv, 'w', newline='', encoding="utf-8") as out_file:
    tsv_writer = csv.writer(out_file, delimiter="\t")
    for idx, row in df_tweetscov19_user.iterrows():
        tsv_writer.writerow(row.values.tolist())